routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\SubSubCategoryController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('home');
});

Route::resource('categories', CategoryController::class);

Route::get('categories/{category}/sub-categories', [CategoryController::class, 'getSubCategories'])->name('categories.sub-categories');

Route::resource('sub-categories', SubCategoryController::class);

Route::get('sub-categories/{sub_category}/sub-sub-categories', [SubCategoryController::class, 'getSubSubCategories'])->name('sub-categories.sub-sub-categories');

Route::resource('sub-sub-categories', SubSubCategoryController::class);

Route::resource('products', ProductController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['sub_sub_category_id', 'title', 'is_active'];

    public function subSubCategory()
    {
        return $this->belongsTo(SubSubCategory::class);
    }
    
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\QueryException;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('subSubCategory.subCategory.category')->latest()->paginate(10);

        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd(count($request->sub_sub_category_id));
        try {
            for($i = 0; $i < count($request->sub_sub_category_id); $i++){
                Product::create([
                    'sub_sub_category_id' => $request->sub_sub_category_id[$i],
                    'title' => $request->title,
                    'is_active' => $request->is_active ?? 0,
                ]);
            }
            
            return redirect()->route('products.index')->withMessage('Successfully Created');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $subCategories = $product->subSubCategory->subCategory->where('id',           $product->subSubCategory->sub_category_id)->get()->toArray();

        $subSubCategories = $product->subSubCategory->where('sub_category_id', $product->subSubCategory->subCategory->id)->get()->toArray();

        return view('products.edit', compact('product', 'subCategories', 'subSubCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        try {
            $product->update([
                'sub_category_id' => $request->category_id,
                'title' => $request->title,
                'is_active' => $request->is_active ?? 0,
            ]);
            return redirect()->route('products.index')->withMessage('Successfully Updated');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        try {
            $product->delete();
            return redirect()->route('products.index')->withMessage('Successfully Deleted');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

app/View/Components/SelectCategory.php
<?php

namespace App\View\Components;

use App\Models\Category;
use Illuminate\View\Component;

class SelectCategory extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */

    public $id;
    public $name;
    public $options;
    public $selected;

    public function __construct($id = null, $name = null, $selected = null)
    {

        $this->id = $id;
        $this->name = $name;
        $this->options = $this->getOptions();
        $this->selected = $selected;
    }

    public function getOptions()
    {
        $options = [];

        foreach (Category::all() as $category){
            $options[] = ['id' => $category->id, 'value' => $category->title];
        }

        return $options;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.forms.select');
    }
}

app/View/Components/SelectSubCategory.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class SelectSubCategory extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */

    public $id;
    public $name;
    public $options;
    public $selected;
    public $categories;

    public function __construct($id = null, $name = null, $selected = null, $categories = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->selected = $selected;
        $this->categories = $categories;
        $this->options = $this->getOptions();
    }

    public function getOptions()
    {
        $options = [];
        // dd($this->categories);
        foreach ($this->categories as $category){
            $options[] = ['id' => $category['id'], 'value' => $category['title']];
        }

        return $options;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.forms.select');
    }
}

resources/views/products/create.blade.php
<x-layout.master>

    <x-slot:title>
        Product
    </x-slot:title>

    <x-slot:pageTitle>
        Product Create
    </x-slot:pageTitle>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('products.store') }}">
                    @csrf
                    <div class="card-body">
                        @if ($errors->any())
                            <x-alerts.errors />
                        @endif

                        <div class="form-group">
                            <x-forms.input name="title" type="text" :value="old('title')" />
                        </div>

                        <div class="form-group">
                            <x-select-category id="category_id" name="category_id" />
                        </div>

                        <div class="form-group">
                            <x-forms.select id="sub_category_id" name="sub_category_id" />
                        </div>

                        <div class="form-group">
                            <x-forms.select id="sub_sub_category_id" name="sub_sub_category_id[]" multiple="multiple" />
                        </div>

                        <div class="form-check">
                            <x-forms.checkbox name="is_active" type="checkbox" value="1" />
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <x-forms.button color="primary" class="mt-2" text="Create" />
                        <x-utilities.link-cancel class="mt-2" href="{{ route('sub-sub-categories.index') }}" />
                    </div>
                </form>
            </div>
        </div>
    </div>



    @push('css')
    @endpush

    @push('js')
        <script>
            let apiUrl = '';

            let option = '<option value="">Please Select One</option>';
            let category =  document.querySelector('#category_id');
            document.querySelector('#sub_category_id').setAttribute('disabled', 'disabled');

            category.addEventListener('change', () => {
                let category_val= category.value;
                let sub_category_id = '#sub_category_id';
                apiUrl = `/categories/${category_val}/sub-categories`;
                getSubCategories(sub_category_id, option, apiUrl);
                
            })

            let select_option = '<option value="">Please Select One</option>';
            let sub_category =  document.querySelector('#sub_category_id');
            document.querySelector('#sub_sub_category_id').setAttribute('disabled', 'disabled');

            sub_category.addEventListener('change', () => {
                let sub_category_val= sub_category.value;
                let sub_category_id = '#sub_sub_category_id';
                apiUrl = `/sub-categories/${sub_category_val}/sub-sub-categories`;
                getSubCategories(sub_category_id, select_option, apiUrl);
                
            })

            const getSubCategories = (sub_category_id, option, apiUrl) => {
                    fetch(apiUrl)
                        .then((res) => res.json())
                        .then((data) => {
                            console.log(data.data);
                            document.querySelector(sub_category_id).removeAttribute('disabled');
                            data.data.forEach((subCategory) => {
                                console.log(subCategory);
                                option += `<option value="${subCategory.id}">
                                    ${subCategory.title}</option>`;
                            })
                            document.querySelector(sub_category_id).innerHTML = option;
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                }

        </script>
    @endpush

</x-layout.master>

resources/views/products/create_back.blade.php
<x-layout.master>

    <x-slot:title>
        Product
    </x-slot:title>

    <x-slot:pageTitle>
        Product Create
    </x-slot:pageTitle>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('products.store') }}">
                    @csrf
                    <div class="card-body">
                        @if ($errors->any())
                            <x-alerts.errors />
                        @endif

                        <div class="form-group">
                            <x-forms.input name="title" type="text" :value="old('title')" />
                        </div>

                        <div class="form-group">
                            <x-select-category id="category_id" name="category_id" />
                        </div>

                        <div class="form-group">
                            <x-forms.select id="sub_category_id" name="sub_category_id" />
                        </div>

                        <div class="form-group">
                            <x-forms.select id="sub_sub_category_id" name="sub_sub_category_id[]" multiple="multiple" />
                        </div>

                        <div class="form-check">
                            <x-forms.checkbox name="is_active" type="checkbox" value="1" />
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <x-forms.button color="primary" class="mt-2" text="Create" />
                        <x-utilities.link-cancel class="mt-2" href="{{ route('products.index') }}" />
                    </div>
                </form>
            </div>
        </div>
    </div>



    @push('css')
    @endpush

    @push('js')
        <script>
            let option = '<option value="">Please Select One</option>';
            let category =  document.querySelector('#category_id');
            document.querySelector('#sub_category_id').setAttribute('disabled', 'disabled');

            category.addEventListener('change', () => {
                let category_val= category.value;
                getSubCategories(category_val);
                
            })

            const getSubCategories = (categoryId) => {
                    const apiUrl = `/categories/${categoryId}/sub-categories`;
                    fetch(apiUrl)
                        .then((res) => res.json())
                        .then((data) => {
                            console.log(data.data);
                            document.querySelector('#sub_category_id').removeAttribute('disabled');
                            data.data.forEach((subCategory) => {
                                console.log(subCategory);
                                option += `<option value="${subCategory.id}">
                                    ${subCategory.title}</option>`;
                            })
                            document.querySelector('#sub_category_id').innerHTML = option;
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                }







            let select_option = '<option value="">Please Select One</option>';
            let sub_category =  document.querySelector('#sub_category_id');
            document.querySelector('#sub_sub_category_id').setAttribute('disabled', 'disabled');

            sub_category.addEventListener('change', () => {
                let sub_category_val= sub_category.value;
                console.log(sub_category_val);
                getSubSubCategories(sub_category_val);
                
            })

            const getSubSubCategories = (sub_category_id) => {
                    const apiUrl = `/sub-categories/${sub_category_id}/sub-sub-categories`;
                    fetch(apiUrl)
                        .then((res) => res.json())
                        .then((data) => {
                            console.log(data.data);
                            document.querySelector('#sub_sub_category_id').removeAttribute('disabled');
                            data.data.forEach((subCategory) => {
                                console.log(subCategory);
                                select_option += `<option value="${subCategory.id}">
                                    ${subCategory.title}</option>`;
                            })
                            document.querySelector('#sub_sub_category_id').innerHTML = select_option;
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                }
        </script>
    @endpush

</x-layout.master>

resources/views/products/edit.blade.php
<x-layout.master>

    <x-slot:title>
        Product
    </x-slot:title>

    <x-slot:pageTitle>
        Product Edit
    </x-slot:pageTitle>
    {{-- @dd($subCategories) --}}
    {{-- @dd($subSubCategories) --}}
{{-- @dd($product->subSubCategory->sub_category_id) --}}
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Product Edit</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('products.update', $product->id) }}">
                    @csrf
                    @method('PATCH')
                    <div class="card-body">
                        @if ($errors->any())
                            <x-alerts.errors />
                        @endif

                        <div class="form-group">
                            <x-forms.input name="title" type="text" :value="old('title', $product->title)" />
                        </div>

                        <div class="form-group">
                            <x-select-category id="category_id" name="category_id"
                            :selected="$product->subSubCategory->subCategory->category_id" />
                        </div>

                        <div class="form-group">
                            <x-select-sub-category id="sub_category_id" name="sub_category_id" 
                            :categories="$subCategories" :selected="$product->subSubCategory->subCategory->id" />
                        </div>

                        <div class="form-group">
                            {{-- <x-forms.select id="sub_sub_category_id" name="sub_sub_category_id[]" multiple="multiple" /> --}}
                            <x-select-sub-category id="sub_sub_category_id" name="sub_sub_category_id[]" multiple="multiple"
                            :categories="$subSubCategories" :selected="$product->subSubCategory->id" />
                        </div>

                        <div class="form-check">
                            <x-forms.checkbox name="is_active" type="checkbox" value="1" 
                            checked="{{ $product->is_active ? 'checked' : '' }}" />
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <x-forms.button color="primary" class="mt-2" text="Update" />
                        <x-utilities.link-cancel class="mt-2" href="{{ route('products.index') }}" />
                    </div>
                </form>
            </div>
        </div>
    </div>



    @push('css')
    @endpush

    @push('js')
        <script>
            let apiUrl = '';

            let option = '<option value="">Please Select One</option>';
            let category =  document.querySelector('#category_id');

            category.addEventListener('change', () => {
                let category_val= category.value;
                let sub_category_id = '#sub_category_id';
                apiUrl = `/categories/${category_val}/sub-categories`;
                getSubCategories(sub_category_id, option, apiUrl);
                
            })

            let select_option = '<option value="">Please Select One</option>';
            let sub_category =  document.querySelector('#sub_category_id');

            sub_category.addEventListener('change', () => {
                let sub_category_val= sub_category.value;
                let sub_category_id = '#sub_sub_category_id';
                apiUrl = `/sub-categories/${sub_category_val}/sub-sub-categories`;
                getSubCategories(sub_category_id, select_option, apiUrl);
                
            })

            const getSubCategories = (sub_category_id, option, apiUrl) => {
                    fetch(apiUrl)
                        .then((res) => res.json())
                        .then((data) => {
                            console.log(data.data);
                            data.data.forEach((subCategory) => {
                                console.log(subCategory);
                                option += `<option value="${subCategory.id}">
                                    ${subCategory.title}</option>`;
                            })
                            document.querySelector(sub_category_id).innerHTML = option;
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                }

        </script>
    @endpush

</x-layout.master>

resources/views/products/index.blade.php
<x-layout.master>

    <x-slot:title>
        Products
    </x-slot:title>

    <x-slot:pageTitle>
        Products
    </x-slot:pageTitle>

    <section class="content">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Products</h3>
                            <x-utilities.link-new class="mt-2" href="{{ route('products.create') }}"
                                style="float:right" />
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if ($errors->any())
                                <x-alerts.errors />
                            @endif

                            <x-alerts.message type="success" :message="session('message')" />

                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Category</th>
                                        <th>Sub Category</th>
                                        <th>Sub Sub Category</th>
                                        <th>Product Title</th>
                                        <th style="white-space:nowrap; text-align:center;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($products as $product)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $product->subSubCategory->subCategory->category->title }}</td>
                                            <td>{{ $product->subSubCategory->subCategory->title }}</td>
                                            <td>{{ $product->subSubCategory->title }}</td>
                                            <td>{{ $product->title }}</td>
                                            <td style="white-space:nowrap; text-align:center;">
                                                <x-utilities.link-show href="{{ route('products.show', $product->id) }}"
                                                    icon="fas fa-solid fa-eye" />

                                                <x-utilities.link-edit href="{{ route('products.edit', $product->id) }}"
                                                    icon="fas fa-solid fa-pen" />


                                                <form method="post"
                                                    action="{{ route('products.destroy', $product->id) }}"
                                                    style="display:inline">
                                                    @csrf
                                                    @method('delete')
                                                    <x-forms.button color="danger"
                                                        onclick="return confirm('Are you sure want to delete?')"
                                                        text="Delete" icon="fas fa-solid fa-trash" />
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            {{ $products->links() }}
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>

    @push('css')
    @endpush

    @push('js')
    @endpush

</x-layout.master>