routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\SubSubCategoryController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('home');
});

Route::resource('categories', CategoryController::class);

Route::get('categories/{category}/sub-categories', [CategoryController::class, 'getSubCategories'])->name('categories.sub-categories');

Route::resource('sub-categories', SubCategoryController::class);

Route::get('sub-categories/{sub_category}/sub-sub-categories', [SubCategoryController::class, 'getSubSubCategories'])->name('sub-categories.sub-sub-categories');

Route::resource('sub-sub-categories', SubSubCategoryController::class);

Route::resource('products', ProductController::class);

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    use HasFactory;

    protected $fillable = ['category_id', 'title', 'is_active'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function subSubCategories()
    {
        return $this->hasMany(SubSubCategory::class);
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\SubCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\QueryException;
use App\Http\Requests\SubCategoryRequest;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subCategories = SubCategory::with('category')->latest()->paginate(10);
        return view('sub_categories.index', compact('subCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sub_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubCategoryRequest $request)
    {
        try {
            SubCategory::create([
                'category_id' => $request->category_id,
                'title' => $request->title,
                'is_active' => $request->is_active ?? 0,
            ]);
            return redirect()->route('sub-categories.index')->withMessage('Successfully Created');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = SubCategory::findOrFail($id);
        return view('sub_categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubCategoryRequest $request, $id)
    {
        try {
            $category = SubCategory::findOrFail($id);
            $category->update([
                'category_id' => $request->category_id,
                'title' => $request->title,
                'is_active' => $request->is_active ?? 0,
            ]);
            return redirect()->route('sub-categories.index')->withMessage('Successfully Updated');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $category = SubCategory::findOrFail($id);
            $category->delete();
            return redirect()->route('sub-categories.index')->withMessage('Successfully Deleted');
        } catch (QueryException $e) {
            Log::error($e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    public function getSubSubCategories(SubCategory $subCategory)
    {
        try {

            return response()->json(
                [
                    'status' => true,
                    'data' => $subCategory->subSubCategories,
                    'message' => 'Success !'
                ]
            );
        } catch (QueryException | Exception $e) {

            Log::error($e->getMessage());

            return response()->json(
                [
                    'status' => false,
                    'data' => [],
                    'message' => 'Somethings went wrong'
                ],
                500
            );
        }
    }
}

app/View/Components/SelectCategory.php
<?php

namespace App\View\Components;

use App\Models\Category;
use Illuminate\View\Component;

class SelectCategory extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */

    public $id;
    public $name;
    public $options;
    public $selected;

    public function __construct($id = null, $name = null, $selected = null)
    {

        $this->id = $id;
        $this->name = $name;
        $this->options = $this->getOptions();
        $this->selected = $selected;
    }

    public function getOptions()
    {
        $options = [];

        foreach (Category::all() as $category){
            $options[] = ['id' => $category->id, 'value' => $category->title];
        }

        return $options;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.forms.select');
    }
}

resources/views/sub_categories/create.blade.php
<x-layout.master>

    <x-slot:title>
        Sub Categories
    </x-slot:title>

    <x-slot:pageTitle>
        Sub Category Create
    </x-slot:pageTitle>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Sub Category Create</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('sub-categories.store') }}">
                    @csrf
                    <div class="card-body">
                        @if ($errors->any())
                            <x-alerts.errors />
                        @endif

                        <div class="form-group">
                            <x-forms.input name="title" type="text" :value="old('title')" />
                        </div>

                        <div class="form-group">
                            <x-select-category id="category_id" name="category_id" />
                        </div>

                        <div class="form-check">
                            <x-forms.checkbox name="is_active" type="checkbox" value="1" />
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <x-forms.button color="primary" class="mt-2" text="Create" />
                        <x-utilities.link-cancel class="mt-2" href="{{ route('sub-categories.index') }}" />
                    </div>
                </form>
            </div>
        </div>
    </div>



    @push('css')
    @endpush

    @push('js')
    @endpush

</x-layout.master>

resources/views/sub_categories/edit.blade.php
<x-layout.master>

    <x-slot:title>
        Sub Categories
    </x-slot:title>

    <x-slot:pageTitle>
        Sub Category Edit
    </x-slot:pageTitle>

    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Sub Category Edit</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('sub-categories.update', $category->id) }}">
                    @csrf
                    @method('PATCH')
                    <div class="card-body">
                        @if ($errors->any())
                            <x-alerts.errors />
                        @endif

                        <div class="form-group">
                            <x-forms.input name="title" type="text" :value="old('title', $category->title)" />
                        </div>

                        <div class="form-group">
                            <x-select-category id="category_id" name="category_id" :selected="$category->category_id" />
                        </div>

                        <div class="form-check">
                            <x-forms.checkbox name="is_active" type="checkbox" value="1"
                                checked="{{ $category->is_active ? 'checked' : '' }}" />
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <x-forms.button color="primary" class="mt-2" text="Update" />
                        <x-utilities.link-cancel class="mt-2" href="{{ route('sub-categories.index') }}" />
                    </div>
                </form>
            </div>
        </div>
    </div>



    @push('css')
    @endpush

    @push('js')
    @endpush

</x-layout.master>

resources/views/sub_categories/index.blade.php
<x-layout.master>

    <x-slot:title>
        Sub Categories
    </x-slot:title>

    <x-slot:pageTitle>
        Sub Category List
    </x-slot:pageTitle>

    <section class="content">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Sub Category List</h3>
                            <x-utilities.link-new class="mt-2" href="{{ route('sub-categories.create') }}" style="float:right" />
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if ($errors->any())
                                <x-alerts.errors />
                            @endif

                            <x-alerts.message type="success" :message="session('message')" />

                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Category</th>
                                        <th>Sub Category Title</th>
                                        <th style="white-space:nowrap; text-align:center;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($subCategories as $category)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $category->category->title }}</td>
                                            <td>{{ $category->title }}</td>
                                            <td style="white-space:nowrap; text-align:center;">
                                                <x-utilities.link-show
                                                    href="{{ route('sub-categories.show', ['sub_category' => $category->id]) }}"
                                                    icon="fas fa-solid fa-eye" />

                                                <x-utilities.link-edit
                                                    href="{{ route('sub-categories.edit', ['sub_category' => $category->id]) }}"
                                                    icon="fas fa-solid fa-pen" />


                                                <form method="post"
                                                    action="{{ route('sub-categories.destroy', $category->id) }}"
                                                    style="display:inline">
                                                    @csrf
                                                    @method('delete')
                                                    <x-forms.button color="danger"
                                                        onclick="return confirm('Are you sure want to delete?')"
                                                        text="Delete" 
                                                        icon="fas fa-solid fa-trash"/>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            {{ $subCategories->links() }}
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>

    @push('css')
    @endpush

    @push('js')
    @endpush

</x-layout.master>